Use ore dictionary for recipe
gigaherz/PackingTape pull request #15
Opened 2018-01-21 02:03 UTC by TheRandomLabs

Closes #14

2018-01-21 16:35 UTC, gigaherz requested changes

2018-01-21 16:35 UTC, gigaherz commented on src/main/resources/assets/packingtape/recipes/packingtape.json
> +        {
Your indentation is a bit weird. Can we get those opening braces aligned properly?

2018-01-22 03:46 UTC, TheRandomLabs commented
Fixed. Not sure how that happened.

2018-01-22 18:02 UTC, gigaherz approved these changes

2018-01-22 18:03 UTC, merged